const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Timer,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.TextBox,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.Destroy,
		C3.Plugins.System.Exps.int
	];
};
self.C3_JsPropNameTable = [
	{Mosaico: 0},
	{Sólido: 0},
	{sensor_Solido: 0},
	{Desenhando: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Piscar: 0},
	{heroGood: 0},
	{Teclado: 0},
	{EstaFeliz: 0},
	{estado: 0},
	{vilaoPasta: 0},
	{Vidas: 0},
	{Áudio: 0},
	{Cronômetro: 0},
	{Hitbox_Ataque: 0},
	{texto_inicial: 0},
	{equip1: 0},
	{equip2: 0},
	{item1: 0},
	{item2: 0},
	{Jussa: 0},
	{TextoCronometro: 0},
	{Senóide: 0},
	{vilaoPixel: 0},
	{ParadaElevador: 0},
	{Elevador2: 0},
	{Emerson: 0},
	{equip3: 0},
	{item3: 0},
	{AJAX: 0},
	{Entrada_Bloqueada: 0},
	{JSON: 0},
	{InputNome: 0},
	{BotaoEnviar: 0},
	{Toque: 0},
	{Mouse: 0},
	{Navegador: 0},
	{area_Morte: 0},
	{Reator: 0},
	{Plano_de_Fundo: 0},
	{Chefe_Final: 0},
	{Projétil: 0},
	{Projetil_Chefe: 0},
	{area_do_chefe: 0},
	{Marcos: 0},
	{Vidas_Chefe: 0},
	{Placa_Indicadora: 0},
	{CronometroAtivo: 0},
	{TempoJogo: 0},
	{SessionToken: 0},
	{VidasChefe: 0}
];

self.InstanceType = {
	Mosaico: class extends self.ITilemapInstance {},
	sensor_Solido: class extends self.ISpriteInstance {},
	heroGood: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	vilaoPasta: class extends self.ISpriteInstance {},
	Vidas: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Hitbox_Ataque: class extends self.ISpriteInstance {},
	texto_inicial: class extends self.ITextInstance {},
	equip1: class extends self.ISpriteInstance {},
	equip2: class extends self.ISpriteInstance {},
	item1: class extends self.ISpriteInstance {},
	item2: class extends self.ISpriteInstance {},
	Jussa: class extends self.ISpriteInstance {},
	TextoCronometro: class extends self.ITextInstance {},
	vilaoPixel: class extends self.ISpriteInstance {},
	Plataforma: class extends self.ISpriteInstance {},
	ParadaElevador: class extends self.ISpriteInstance {},
	Elevador2: class extends self.ISpriteInstance {},
	Emerson: class extends self.ISpriteInstance {},
	equip3: class extends self.ISpriteInstance {},
	item3: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Entrada_Bloqueada: class extends self.ISpriteInstance {},
	JSON: class extends self.IJSONInstance {},
	InputNome: class extends self.ITextInputInstance {},
	BotaoEnviar: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Navegador: class extends self.IInstance {},
	area_Morte: class extends self.ISpriteInstance {},
	Reator: class extends self.ISpriteInstance {},
	Plano_de_Fundo: class extends self.ISpriteInstance {},
	Chefe_Final: class extends self.ISpriteInstance {},
	Projetil_Chefe: class extends self.ISpriteInstance {},
	area_do_chefe: class extends self.ISpriteInstance {},
	Marcos: class extends self.ISpriteInstance {},
	Vidas_Chefe: class extends self.ISpriteInstance {},
	Placa_Indicadora: class extends self.ISpriteInstance {}
}